### ISSUE TITLE
ProtocolError: <ProtocolError for localhost:8080/pentaho-reports-for-odoo: 404 Not Found>

### ISSUE THREAD

**Issue by sebytza05** [WilldooIT/Pentaho-Odoo#9]
Hello guys,
We are trying to install pentaho-reports on Odoo 10. 
When I try to run an uploaded report I receive this error: 

Traceback (most recent call last):
  File "/odoo10/odoo10-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo10/odoo10-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo10/odoo10-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo10/odoo10-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo10/odoo10-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo10/odoo10-server/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo10/odoo10-server/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo10/odoo10-server/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo10/odoo10-server/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/models.py", line 1329, in load_views
    for [v_id, v_type] in views
  File "/odoo10/odoo10-server/odoo/models.py", line 1329, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo10/custom/addons/pentaho_reports/wizard/report_prompt.py", line 346, in fields_view_get
    parameters = self._setup_parameters(report_action)
  File "/odoo10/custom/addons/pentaho_reports/wizard/report_prompt.py", line 198, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for localhost:8080/pentaho-reports-for-odoo: 404 Not Found>

The report was made using Pentaho report designer.
Can you tell me how can I solve this? 
I used Pentaho on Odoo 8 version without problems.

**Comment by richard-willdooit** [comment]
Did you check the service is running on pentaho-reports-for-odoo and not pentaho-reports-for-openerp?






[https://mail.google.com/mail/u/0/?ui=2&ik=49665902db&view=fimg&th=160f72c872be2c79&attid=0.0.2&disp=emb&attbid=ANGjdJ_2xwtePEvQujZxydhUpkuw7dDtyuJ6A7Zkt9sH739Gbbv7e17hYqMV18pTlKe92v11ALjghylqONECDSYJJle7dtn-zsNu3asa7USIhV_5lvkFJmoaL8LLbmU&sz=w396-h250&ats=1516570381278&rm=160f72c872be2c79&zw&atsh=1]<https://www.willdooit.com/>


Richard deMeeseter

Senior Development Analyst

WilldooIT Pty Ltd

E: richard.demeester@willdooit.com<mailto:richard.demeester@willdooit.com>

M: +61 403 76 76 76<tel:+61%20403%2076%2076%2076>

P: +61 3 9135 1900<tel:+61%203%209135%201900>

A: 10/435 Williamstown Road, Port Melbourne, Vic 3207







Our vision is to provide end to end IT solutions to help our clients achieve their desired objectives and provide growth opportunities for everyone working in the company to reach their full professional potential.



[cid:image005.png@01D33CFB.CF033C70]<https://www.pnors.com/>



- Celebrating 35 Years -

DISCLAIMER | This electronic message together with any attachments is confidential. If you are not the recipient, do not copy, disclose, or use the contents in any way. Please also advise us by e-mail that you have received this message in error and then please destroy this email and any of its attachments. WilldooIT Pty. Ltd. is not responsible for any changes made to this message and/or any attachments after sending by WilldooIT Pty. Ltd. WilldooIT Pty. Ltd. use virus scanning software but exclude all liability for virus or anything similar in this email or attachment.




________________________________
